galaxy_info:
  role_name: ca
  namespace: Name1essGuy
  author: Name1essGuy
  description: A role for Certificate Authority server creation

  license: BSD-3-Clause

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
      - jammy

  galaxy_tags:
    - web
    - nginx

dependencies: []