dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vpn-test-instance
    image: "ubuntu:22.04"
    pre_build_image: false
    dockerfile: |
      FROM ubuntu:22.04
      RUN apt-get update && \
          apt-get install -y python3 sudo && \
          rm -rf /var/lib/apt/lists/*
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ovpn_server_dir: /etc/openvpn/server
        ovpn_username: vpn-admin
        ovpn_user_password: password
        ovpn_group: vpn-ops
        ca_server: ca_server
        ca_dir: /etc/CA/server
        required_packages: "{{ packages }}"
        required_groups:
          - "{{ ca_group }}"
        reuired_users:
          - "{{ ca_username }}"
verifier: 
  name: ansible
