---

- name: Install packages
  ansible.builtin.apt:
    name:
      - prometheus-nginx-exporter
    update_cache: true

- name: Create system group
  ansible.builtin.group:
    name: prometheus
    state: present
    system: true

- name: Create system user
  ansible.builtin.user:
    name: nginx_exporter
    comment: prometheus nginx exporter system user
    group: prometheus
    shell: /usr/sbin/nologin # sbin/nologin
    home: "/nonexistent"
    system: true

- name: Copy systemd unit fo exporter
  ansible.builtin.copy:
    src: systemd/prometheus-nginx-exporter.service
    dest: /etc/systemd/system/prometheus-nginx-exporter.service

- name: Start exporter as system user
  ansible.builtin.systemd_service:
    name: prometheus-nginx-exporter.service
    state: started
    enabled: yes
    daemon_reload: true