---

- name: Install packages
  ansible.builtin.apt:
    name:
      - prometheus-node-exporter
    update_cache: true

- name: Create system group
  ansible.builtin.group:
    name: prometheus
    state: present
    system: true

- name: Create system user
  ansible.builtin.user:
    name: node_exporter
    comment: prometheus node exporter system user
    group: prometheus
    shell: /usr/sbin/nologin # sbin/nologin
    home: "/nonexistent"
    system: true

- name: Copy systemd unit
  ansible.builtin.copy:
    src: systemd/prometheus-node-exporter.service
    dest: /etc/systemd/system/prometheus-node-exporter.service

- name: Start exporter as system user
  ansible.builtin.systemd_service:
    name: prometheus-node-exporter.service
    state: started
    enabled: yes
    daemon_reload: true