---

- name: Install openvpn
  ansible.builtin.apt:
    name:
      - openvpn
    udpate_cache: true

- name: Enable ip forwarding
  ansible.builtin.lineinfile:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    line: net.ipv4.ip_forward=1
  bash: sysctl -p /etc/sysctl.conf

- name: Create service group and user
  ansible.builtin.group:
    name: "{{ ovpn_group }}"
    state: present
    system: yes
  ansible.builtin.user:
    name: "{{ ovpn_username}}"
    comment: service account for easy-rsa
    group: "{{ ovpn_group}}"
    shell: /usr/sbin/nologin #/sbin/nologin
    home: "/nonexistent"
    password: "{{ ovpn_user_password | password_hash('sha512') }}"
    system: yes
