---

- name: Dowload necessary files from CA server to VPN
  # Скачать файлы с удалённого сервера на устройсвто, с которого происходяит запуск плейбука
  ansible.builtin.fetch:
    src: "{{ item.src }}"
    dest: "/tmp/OVPN/{{ item.filename }}"
    flat: yes
  loop:
    - { src: "{{ ca_dir }}/pki/ca.crt", filename: "ca.crt" }
    - { src: "{{ ca_dir }}/pki/issued/server.crt", filename: "server.crt" }
  delegate_to: "{{ ca_server }}"
  run_once: yes
  # Скопировать файлы с устройства, на котором происходит запуск плейбука на удалённый сервер
  anscible.builtin.copy:
    src: "/tmp/OVPN/{{ item.filename }}"
    dest: "{{ ovpn_server_dir }}/{{ item.filename }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { filename: "ca.crt", owner: "{{ ovpn_username }}", group: "{{ ovpn_group }}", mode: "u=rwx,g=rx,o=" }
    - { filename: "server.crt", owner: "{{ ovpn_username }}", group: "{{ ovpn_group }}", mode: "u=rwx,g=rx,o=" }

- name: Generate TLS key
  cmd: "openvpn --genkey secret ta.key"
  args:
    chdir: "{{ ovpn_server_dir }}"  
  become_user: "{{ ovpn_username }}"
  ansible.builtin.file:
    path: "{{ ovpn_server_dir }}/ta.key"
    owner: "{{ ovpn_username }}"
    group: "{{ ovpn_group }}"
    mode: "u=rwx,g=rx,o=" # 0750

- name: Copy server config
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ ovpn_server_dir }}/server.conf"
    owner: "{{ ovpn_username }}"
    gruop: "{{ ovpn_group }}"
    mode: "u=rwx,g=rx,o=" # 0750

- name: Enable and start OVPN server
  ansible.builtin.sustemd_service:
    name: openvpn@server
    state: started
    enabled: yes