---

- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
    update_cache: true

- name: Create service group and user
  ansible.builtin.group:
    name: "{{ web_group }}"
    state: present
    system: yes
  ansible.builtin.user:
    name: "{{ web_username }}"
    comment: service user for nginx
    group: "{{ web_group }}"
    shell: /usr/sbin/nologin #/sbin/nologin
    home: "/nonexistent"
    password: "{{ web_user_password | password_hash('sha512') }}"
    system: yes

- name: Run nginx by system user
  ansible.builtin.systemd_service:
    name: nginx
    state: stopped
  ansible.builtin.template:
    src: "systemd/nginx.service.j2"
    dest: "/etc/systemd/system/nginx.service"
  ansible.builtin.systemd_service:
    name: nginx.service
    state: started
    enabled: true
    daemon_reload: true
