---

- name: Allow prometheus exporters
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destintion_port: "{{ item.port }}"
    match: conntrack
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: "{{ item.comment }}"
  loop:
    - { port: "{{ node_exporter_port }}", comment: "Allow prometheus node exporter connections" }
    - { port: "{{ process_exporter_port }}", comment: "Allow prometheus process exporter connections" }
    - { port: "{{ mysqld_exporter_port }}", comment: "Allow prometheus mysqld exporter connections" }

- name: Allow MySQL connections and responses
  ansible.builtin.iptables:
    chain: INPUT,OUTPUT
    protocol: tcp
    destintion_port: 3306
    match: conntrack
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: "Allow MySQL connections and responses"

# Скопировать бэкапный bash скрипт для настройки фаерволла на целевую машину (на всякий случай)
- name: Create directory
  ansible.builtin.file:
    path: /var/lib/firewall
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=" # 0750

- name: Copy rules script
  ansible.builtin.template:
    src: iptables/iptables_db.sh.j2
    dest: /var/lib/firewall/iptables_db.sh
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=" # 0750

- name: Restart iptables
  ansible.builtin.systemd_service:
    name: iptables
    state: restarted